export enum AuditedAction {
	Artist_Create = 'Artist_Create',
	Artist_Delete = 'Artist_Delete',
	Artist_Update = 'Artist_Update',
	Quote_Create = 'Quote_Create',
	Quote_Delete = 'Quote_Delete',
	Quote_Update = 'Quote_Update',
	Translation_Create = 'Translation_Create',
	Translation_Delete = 'Translation_Delete',
	Translation_Update = 'Translation_Update',
	User_ChangeEmail = 'User_ChangeEmail',
	User_ChangePassword = 'User_ChangePassword',
	User_Create = 'User_Create',
	User_FailedLogin = 'User_FailedLogin',
	User_Login = 'User_Login',
	User_Rename = 'User_Rename',
	Work_Create = 'Work_Create',
	Work_Delete = 'Work_Delete',
	Work_Update = 'Work_Update',
}
