export enum WordCategory {
	Noun = 'noun',
	Verb = 'verb',
	Adjective = 'adjective',
	AdjectivalNoun = 'adjectival-noun',
	Adverb = 'adverb',
	PostpositionalParticle = 'postpositional-particle',
	AuxiliaryVerb = 'auxiliary-verb',
	Attributive = 'attributive',
	Conjunction = 'conjunction',
	Prefix = 'prefix',
	Suffix = 'suffix',
	Interjection = 'interjection',
	Other = 'other',
	Pronoun = 'pronoun',
}
