export enum Permission {
	CreateArtists = 'CreateArtists',
	CreateQuotes = 'CreateQuotes',
	CreateTranslations = 'CreateTranslations',
	CreateWorks = 'CreateWorks',
	DeleteArtists = 'DeleteArtists',
	DeleteQuotes = 'DeleteQuotes',
	DeleteTranslations = 'DeleteTranslations',
	DeleteWorks = 'DeleteWorks',
	EditArtists = 'EditArtists',
	EditQuotes = 'EditQuotes',
	EditTranslations = 'EditTranslations',
	EditWorks = 'EditWorks',
	ViewDeletedEntries = 'ViewDeletedEntries',
	ViewEditHistory = 'ViewEditHistory',
	ViewHiddenEntries = 'ViewHiddenEntries',
}
