export enum Permission {
	CreateArtistLinks = 'CreateArtistLinks',
	CreateArtists = 'CreateArtists',
	CreateMissingRevisions = 'CreateMissingRevisions',
	CreateQuotes = 'CreateQuotes',
	CreateTranslations = 'CreateTranslations',
	CreateWebLinks = 'CreateWebLinks',
	CreateWorkLinks = 'CreateWorkLinks',
	CreateWorks = 'CreateWorks',
	DeleteArtistLinks = 'DeleteArtistLinks',
	DeleteArtists = 'DeleteArtists',
	DeleteQuotes = 'DeleteQuotes',
	DeleteTranslations = 'DeleteTranslations',
	DeleteWebLinks = 'DeleteWebLinks',
	DeleteWorkLinks = 'DeleteWorkLinks',
	DeleteWorks = 'DeleteWorks',
	UpdateArtistLinks = 'UpdateArtistLinks',
	UpdateArtists = 'UpdateArtists',
	UpdateQuotes = 'UpdateQuotes',
	UpdateSearchIndex = 'UpdateSearchIndex',
	UpdateTranslations = 'UpdateTranslations',
	UpdateWebLinks = 'UpdateWebLinks',
	UpdateWorkLinks = 'UpdateWorkLinks',
	UpdateWorks = 'UpdateWorks',
	ViewDeletedEntries = 'ViewDeletedEntries',
	ViewHiddenEntries = 'ViewHiddenEntries',
	ViewRevisions = 'ViewRevisions',
}
